package gov.nih.niehs.notification.model;

import java.util.Objects;
import java.util.UUID;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import org.springframework.validation.annotation.Validated;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * BulkNotificationOptStatusInner
 */
@Validated
public class BulkNotificationOptStatusInner {

	public BulkNotificationOptStatusInner(UUID notificationId, Boolean operationStatus) {
		super();
		this.notificationId = notificationId;
		this.operationStatus = operationStatus;
	}

	@JsonProperty("notification_id")
	private UUID notificationId = null;

	@JsonProperty("operation_status")
	private Boolean operationStatus = null;

	public BulkNotificationOptStatusInner notificationId(UUID notificationId) {
		this.notificationId = notificationId;
		return this;
	}

	/**
	 * an unique uuid auto-generated by postgres db
	 * 
	 * @return notificationId
	 **/
	@ApiModelProperty(required = true, value = "an unique uuid auto-generated by postgres db")
	@NotNull

	@Valid
	public UUID getNotificationId() {
		return notificationId;
	}

	public void setNotificationId(UUID notificationId) {
		this.notificationId = notificationId;
	}

	public BulkNotificationOptStatusInner operationStatus(Boolean operationStatus) {
		this.operationStatus = operationStatus;
		return this;
	}

	/**
	 * Get operationStatus
	 * 
	 * @return operationStatus
	 **/
	@ApiModelProperty(required = true, value = "")
	@NotNull

	public Boolean isOperationStatus() {
		return operationStatus;
	}

	public void setOperationStatus(Boolean operationStatus) {
		this.operationStatus = operationStatus;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		BulkNotificationOptStatusInner bulkNotificationOptStatusInner = (BulkNotificationOptStatusInner) o;
		return Objects.equals(this.notificationId, bulkNotificationOptStatusInner.notificationId)
				&& Objects.equals(this.operationStatus, bulkNotificationOptStatusInner.operationStatus);
	}

	@Override
	public int hashCode() {
		return Objects.hash(notificationId, operationStatus);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class BulkNotificationOptStatusInner {\n");

		sb.append("    notificationId: ").append(toIndentedString(notificationId)).append("\n");
		sb.append("    operationStatus: ").append(toIndentedString(operationStatus)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}
}
